CREATE TABLE IF NOT EXISTS kalam (
             id INTEGER PRIMARY KEY,
             text TEXT NOT NULL,
             text_fr TEXT NOT NULL,
             couplet INTEGER NOT NULL,
             baid INTEGER NOT NULL);



    CREATE TABLE IF NOT EXISTS baid (
             id INTEGER PRIMARY KEY,
             fassil TEXT NOT NULL);



INSERT or IGNORE INTO baid  (id,fassil) VALUES (1,"فصل الأول في الغزل وشكوى الغرام");
INSERT or IGNORE INTO baid  (id,fassil) VALUES (2,"فضل الثاني في التحذيرمن هو النفس");
INSERT or IGNORE INTO baid  (id,fassil) VALUES (3,"الفصل الثالث في مدح سيدنا النبي صلى الله عليه وسلم");
INSERT or IGNORE INTO baid  (id,fassil) VALUES (4,"الفصل الرابع في مولده صلى الله عليه وسلم");
INSERT or IGNORE INTO baid  (id,fassil) VALUES (5,"الفصل الخامس في معجزاته صلى الله عليه وسلمِ");
INSERT or IGNORE INTO baid  (id,fassil) VALUES (6,"الفصل السادس في شرف القرآن ومدحه");
INSERT or IGNORE INTO baid  (id,fassil) VALUES (7,"الفصل السابع في إسرائه ومعراجه صلى الله عليه وسلم");
INSERT or IGNORE INTO baid  (id,fassil) VALUES (8,"الفصل الثامن في جهاد سيدنا النبي صلى الله عليه وسلم");
INSERT or IGNORE INTO baid  (id,fassil) VALUES (9,"الفصل التاسع في التوسل بسيدنا رسول الله صلى الله عليه وسلم");
INSERT or IGNORE INTO baid  (id,fassil) VALUES (10,"الفصل العاشر في المناجات وعرض الحاجات");


INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (1,"اَمِنْ تَذَكُّرِ جِيرَانٍ بِذِي سَلَمِ"," Le souvenir des voisins que tu as laissés à Dû-Salem est-il la cause de tes pleurs ? ",1,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (2,"مَزَجْتَ دَمْعاً جَرَىٰ مِنْ مُقْلَةٍ بِدَمِ","Quel sujet fait couler de tes yeux des larmes mêlées de sang ?",1,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (3,"اَمْ هَبَّتِ الرِّيحُ مِنْ تِلْقَاءِ كَاظِمَةٍ","Est-ce le vent qui, soufflant du côté de Kadhéma, les rappelle à ta mémoire ",2,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (4,"وَاَوْمَضَ الْبَرْقُ فِي الظَّلْمَاءِ مِنْ إِضَمِ","Ou l'éclair brillant au milieu de l'obscurité, sur les hauteurs d'Idham, découvre-t-il à tes regards le lieu qu'ils habitent ? ",2,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (5,"فَمَا لِعَيْنَيْكَ إِنْ قُلْتَ اكْفُفَا هَمَتَا","Pourquoi tes yeux versent-ils des torrents d'eau, lors même que tu leur ordonnes de retenir leurs larmes? ",3,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (6,"وَمَا لِقَلْبِكَ إِنْ قُلْتَ اسْتَفِقْ يَهِمِ","Pourquoi ton cœur, au moment où tu lui dis : Reviens à toi, est-il dans une violente agitation ? ",3,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (7,"اَيَحْسَبُ الصَّبُّ اَنَّ الْحُبَّ مُنْكَتِمٌ","Celui que l'amour possède s'imagine-t-il tenir cachée la passion qui l'agite,",4,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (8,"مَا بَيْنَ مُنْسَجِمٍ مِنْهُ وَمُضْطَرِمِ","Lorsque deux parties de lui-même trahissent son secret ; ses yeux qui fondent en pleurs, et son cœur que consume une flamme ardente ? ",4,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (9,"لَوْلَا الْهَوَىٰ لَمْ تُرِقْ دَمْعاً عَلَىٰ طَلَلِ","Ah ! Si l'amour n'était la cause de ta peine, on ne te verrait pas verser des larmes sur les débris d'une habitation abandonnée ",5,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (10,"وَلَا اَرِقْتَ لِذِكْرِ الْبَانِ وَالْعَلَمِ ","Le souvenir de ce ban [1] et de cette colline ne te ravirait pas le sommeil. ",5,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (11,"فَكَيْفَ تُنْكِرُ حُبّاً بَعْدَمَا شَهِدَتْ","Et comment pourrais-tu nier que tu sois en proie aux tourments de l'amour",6,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (12,"بِهِ عَلَيْكَ عُدُولُ الدَّمْعِ وَالسَّقَمِ"," Lorsque deux témoins irréprochables déposent contre toi, les pleurs que tu répands, et la maladie qui le consume.",6,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (13,"وَاَثْبَتَ الْوَجْدُ خَطَّيْ عَبْرَةٍ وَضَنَىٰ","Lorsque la violence de ta passion a écrit ta conviction sur tes joues ",7,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (14,"مِثْلَ الْبَهَارِ عَلَىٰ خَدَّيْكَ وَالْعَنَمِ","En y traçant les deux lignes des pleurs et de la maigreur, et en leur imprimant les couleurs de la rose jaune et du bois d'anem ? ",7,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (15,"نَعَمْ سَرَىٰ طَيْفُ مَنْ اَهْوَىٰ فَأَرَّقَنِي","Oui, l'ombre de ce que j'aime est venue me ravir le sommeil",8,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (16,"وَالْحُبُّ يَعْتَرِضُ اللَّذَّاتِ بِالْأَلَمِ"," Tel est l'effet de l'amour, il change nos plaisirs en cruels tourments. ",8,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (17,"يَا لَائِمِي فِي الْهَوَى الْعُذْرِيِّ مَعْذِرَةً","O toi qui me reproches la violence d'un amour insurmontable, ma faiblesse est digne d'excuse ",9,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (18,"مِنِّي إِلَيْكَ وَلَوْ اَنْصَفْتَ لَم تَلُمِ","Et si tu étais équitable, tu m'épargnerais tes réprimandes. ",9,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (19,"عَدَتْكَ حَالِيَ لَا سِرِّي بمُسْتَتِرٍ","Puissent les maux que j'éprouve retomber sur toi !  ",10,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (20,"عَنِ الْوُشَاةِ وَلَا دَائِي بِمُنْحَسِمِ","Mon secret ne saurait échapper aux regards des délateurs, et le mal qui me mine n'admet point de guérison.",10,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (21,"مَحَّضْتَنِي النُّصْحَ لَـٰكِنْ لَسْتُ اَسْمَعُهُ","Tu m'as donné de sages avis, mais je n'étais pas capable de les entendre ",11,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (22,"إِنَّ الْمُحِبَّ عَنِ الْعُذَّالِ فِي صَمَمِ","Car celui que l'amour domine est sourd à toutes les censures. ",11,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (23,"إِنِّي اتَّهَمْ تُ نَصِيحَ الشَّيْبِ فِي عَذَلِي","La vieillesse même aux cheveux blancs n'a pas été à l'abri de mes soupçons injurieux lorsqu’elle a voulu, par ses conseils, réformer ma conduite",12,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (24,"وَالشَّيْبُ اَبْعَدُ فِي نُصْحٍ عَنِ التُّهَمِ"," Et cependant est-il des conseils moins suspects que ceux que donne la vieillesse ? ",12,1);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (25,"فَإِنَّ اَمَّارَتِي بِالسُّوءِ مَا اتَّعَظَتْ","Dans sa folie, le penchant violent qui m'entraîne vers le mal",13,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (26,"مِنْ جَهْلِهَا بِنَذِيرِ الشَّيْبِ وَالْهَرَمِ","N’a point mis à profit les sages avertissements des cheveux blancs et de l'âge décrépit. ",13,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (27,"وَلَا اَعَدْتُّ مِنَ الْفِعْلِ الْجَمِيلِ قِرَىٰ","Incapable d'aucune bonne action",14,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (28,"ضَيْفٍ اَلَمَّ بِرَأْسِي غَيْرَ مُحْتَشِمِ","Mon âme corrompue n'a pas même offert un repas hospitalier à l'hôte respectable qui était venu sans façon chercher l'hospitalité près de moi. ",14,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (29,"لَوْ كُنْتُ اَعْلَمُ اَنِّي مَا أُوَقِّرُهُ","Ah ! Si j'eusse prévu que je ne lui rendrais pas les honneurs qui lui étaient dus",15,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (30,"كَتَمْتُ سِرّاً بَدَا لِي مِنْهُ بِالْكَتَمِ","J’aurais déguisé par le jus du katam son secret que j'ai aperçu [2] ",15,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (31,"مَنْ لِي بِرَدِّ جِمَاحٍ مِنْ غَوَايَتِهَا","Qui ramènera de son égarement cette volonté rebelle et indomptable",16,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (32,"كَمَا يُرَدُّ جِمَاحُ الْخَيْلِ بِاللُّجُمِ","Ainsi que l'on gouverne avec un frein le cheval le plus fougueux ! ",16,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (33,"فَلَا تَرُمْ بِالْمَعَاصِي كَسْرَ شَهْوَتِهَا","Ne te flatte pas d'amortir la violence de ses passions, en t'abandonnant aux actions criminelles.",17,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (34,"إِنَّ الطَّعَامَ يُقَوِّي شَهْوَةَ النَّهِمِ","Telle la nourriture ne sert qu'à augmenter la violence d'un appétit déréglé. ",17,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (35,"وَالنَّفْسُ كَالطِّفْلِ إِنْ تُهْمِلْهُ شَبَّ عَلَىٰ","L'âme est semblable à un tendre enfant : si on le laisse suivre son penchant",18,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (36,"حُبِّ الرِّضَاعِ وَإِنْ تَفْطِمْهُ يَنفَطِمِ","Il conservera en grandissant l'amour du lait maternel ; mais si on l'en prive, il se sèvrera de cet aliment. ",18,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (37,"فَاصْرِفْ هَوَاهَا وَحَاذِرْ اَنْ تُوَلِّيَهُ","Détourne donc ton âme de l'amour auquel elle se livre, garde-toi de souffrir qu'il domine chez elle",19,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (38,"إِنَّ الْهَوَىٰ مَا تَوَلَّىٰ يُصْمِ اَوْ يَصِمِ","Car où l'amour règne sans obstacle, il donne la mort, ou bien il couvre d'ignominie. ",19,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (39,"وَرَاعِهَا وَهْيَ فِي الْأَعْمَالِ سَائِمَةٌ","Veille sur elle au milieu de ses actions, ainsi qu'un berger veille sur ses troupeaux au milieu des pâturages",20,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (40,"وَإِنْ هِيَ اسْتَحْلَتِ الْمَرْعَىٰ فَلَا تُسِمِ","Et quand même le pâturage lui paraîtrait agréable, ne permets pas qu'elle y paisse à son gré. ",20,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (41,"كَمْ حَسَّنَتْ لَذَّةً  لِلْمَرْءِ قَاتِلَةً","Combien d'hommes l'attrait de la concupiscence n'a-t-il pas séduits, en leur présentant, sous une apparence favorable, des plaisirs qui leur ont donné la mort !",21,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (42,"مِنْ حَيْثُ لَمْ يَدْرِ اَنَّ السُّمَّ فِي الدَّسَمِ","Ils ignoraient que le poison est caché dans les mets les plus délicats. ",21,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (43,"وَاخْشَ الدَّسَائِسَ مِنْ جُوعٍ وَمِنْ شِبَعٍ","Crains également les pièges cachés de la faim et ceux de la satiété. ",22,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (44,"فَرُبَّ مَخْمَصَةٍ شَرٌّ مِنَ التُّخَمِ","Souvent une faim violente est pire encore que les maux qui suivent l'excès de la nourriture. ",22,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (45,"وَاسْتَفْرِغِ الدَّمْعَ مِنْ عَيْنٍ قَدِ امْتَلَأَتْ","Que tes yeux qui ont été remplis de crimes se purifient par des larmes abondantes",23,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (46,"مِنَ الْمَحَارِمِ وَالْزَمْ حِميَةَ النَّدَمِ","Et ne quitte jamais l'asile de la repentance. ",23,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (47,"وَخَالِفِ النَّفْسَ وَالشَّيْطَانَ وَاعْصِهِمَا","Résiste à la concupiscence et à Satan, et sois rebelle à leurs suggestions",24,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (48,"وَإِنْ هُمَا مَحَضَاكَ النُّصْحَ فَاتَّهِمِ","Quand même ils te donneraient des conseils sages en apparence, tiens-les toujours pour suspects. ",24,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (49,"وَلَا تُطِعْ مِنْهُمَا خَصْماً وَلَا حَكَماً","Ne leur obéis jamais, soit qu'ils manifestent la malice d'un ennemi, ou qu'ils se couvrent des apparences d'une impartiale justice",25,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (50,"فَأَنْتَ تَعْرِفُ كَيْدَ الْخَصْمِ وَالْحَكَمِ","Car tu connais les pièges que tendent et ces ennemis manifestes, et ces conciliateurs insidieux. ",25,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (51,"اَسْتَغْفِرُ اللهَ مِنْ قَوْلٍ بِلَا عَمَلٍ","Je demande pardon à mon Dieu de ce que mes discours ne sont point accompagnés d'une conduite qui leur soit conforme.",26,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (52,"لَقَدْ نَسَبْتُ بِهِ نَسْلاً لِذِي عُقُمِ","Mon inconséquence est la même que si j'attribuais une postérité à un homme que la nature aurait frappé de stérilité. ",26,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (53,"اَمَرْتُكَ الْخَيْرَ لَـٰكِنْ مَائْتَمَرْتُ بِهِ","Je t'ai donné des leçons de vertu dont moi-même je n'ai pas fait la règle de mes actions.",27,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (54,"وَمَا اسْتَقَمْتُ فَمَا قَوْلِي لَكَ اسْتَقِمِ","Je n'ai point redressé ma conduite, m'appartient-il de te dire : Redresse-toi ? ",27,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (55,"وَلَا تَزَوَّدْتُ قَبْلَ الْمَوْتِ نَافِلَةً","J'ai négligé d'amasser avant la mort une provision de bonnes œuvres pour le temps de mon voyage.",28,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (56,"وَلَمْ أُصَلِّ سِوَىٰ فَرْضٍ وَلَمْ اَصُمِ","Je n'ai ajouté ni prières ni jeûnes à ceux dont l'obligation est d'une indispensable nécessité. ",28,2);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (57,"ظَلَمْتُ سُنَّةَ مَنْ اَحْيَا الظَّلَامَ إِلىٰ","J'ai criminellement omis de me conformer à l'exemple de celui [3] qui vivifiait les nuits en les passant en prières,",29,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (58,"اَنِ اشْتَكَتْ قَدَمَاهُ الضُّرَّ مِنْ وَرَمِ","Jusque-là que ses pieds fatigués par la longueur de ses veilles en contractaient des tumeurs douloureuses ; ",29,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (59,"وَشَدَّ مِنْ سَغَبٍ اَحْشَاءَهُ وَطَوَىٰ","Qui, épuisé par des jeûnes assidus, était obligé de serrer par des ligatures ses entrailles affamées,",30,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (60,"تَحْتَ الْحِجَارَةِ كَشْحَاً مُتْرَفَ الْأَدَمِ","Et de comprimer avec des pierres la peau fine de ses flancs délicats. ",30,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (61,"وَرَاوَدَتْهُ الْجِبَالُ الشُّمُّ مِنْ ذَهَبٍ","Des montagnes d'or d'une élévation prodigieuse ont sollicité l'honneur de lui appartenir ;",31,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (62,"عَنْ نَفْسِهِ فَأَرَاهَا اَيَّمَا شَمَمِ","Mais il leur a fait voir quelque chose de bien plus élevé, par son mépris pour les biens de ce monde. ",31,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (63,"وَاَكَّدَتْ زُهْدَهُ فِيهَا ضَرُورَتُهُ","La nécessité qui le pressait ajoutait un nouveau mérite à son détachement ;",32,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (64,"إِنَّ الضَّرُورَةَ لَا تَعْدُو عَلَى الْعِصَمِ","Les suggestions du besoin ne purent triompher de son désintéressement. ",32,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (65,"وَكَيْفَ تَدْعُو إِلَى الدُّنْيَا ضَرُورَةُ مَنْ","Que dis-je ? Le besoin pouvait-il inspirer le désir des biens de ce mondé,",33,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (66,"لَوْلَاهُ لَمْ تُخْرَجِ الدُّنْيَا مِنَ الْعَدَمِ","À celui sans lequel le monde ne serait jamais sorti du néant? ",33,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (67,"مُحَمَّدٌّ سَيِّدُ الْكَوْنَيْنِ وَالثَّقَلَيْنِ","MUHAMMAD est le prince des deux mondes, des hommes et des génies,",34,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (68,"وَالْفَرِيقَيْنِ مِنْ عُرْبٍ وَمِنْ عَجَمِ","Le souverain des deux peuples, ceux qui parlent l’arabe et ceux qui parlent des langues différentes. ",34,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (69,"نَبِيُّنَا الْآمِرُ النَّاهِي فَلَا اَحَدٌ","Il est notre prophète, qui nous prescrit ce que nous devons faire, et nous défend ce que nous devons éviter.",35,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (70,"اَبَرَّ فِي قَوْلِ لَا مِنْهُ وَلَا نَعَمِ","Il est le plus véridique de tous les hommes, soit qu'il affirme, soit qu'il nie. ",35,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (71,"هُوَ الْحَبِيبُ الَّذِي تُرْجَىٰ شَفَاعَتُهُ","Il est l'ami de Dieu ; il est celui dont l'intercession est l'unique fondement de notre espoir",36,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (72,"لِكُلِّ هَوْلٍ مِنَ الْأَهوَالِ مُقْتَحِمِ","Et notre ressource contre les dangers les plus affreux. ",36,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (73,"دَعَا إِلى اللهِ فَالْمُسْتَمْسِكُونَ بِهِ","Il a appelé les mortels à la connaissance de Dieu, et quiconque s'attache à lui",37,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (74,"مُسْتَمْسِكُونَ بِحَبْلٍ غَيْرِ مُنْفَصِمِ","S’attache à une corde qui n'est point sujette à se rompre. ",37,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (75,"فَاقَ النَّبِيِّينَ فِي خَلْقٍ وَفِي خُلُقٍ","Il a surpassé tous les autres prophètes par l'excellence de ses qualités extérieures et de ses qualités morales.",38,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (76,"وَلَمْ يُدَانُوهُ فِي عِلْمٍ وَلَا كَرَمِ","Aucun d'eux n'approche de lui en science ni en vertu. ",38,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (77,"وَكُلُّهُمْ مِنْ رَسُولِ اللهِ مُلْتَمِسٌ","Chacun d'eux sollicite de l'apôtre de Dieu une gorgée de la mer de sa science,",39,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (78,"غَرْفاً مِنَ الْبَحْرِ اَوْ رَشْفاً مِنَ الدِّيَمِ","Ou une goutte des pluies abondantes de sa vertu. ",39,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (79,"وَوَاقِفُونَ لَدَيْهِ عِنْدَ حَدِّهِمُ","Ils se tiennent près de lui dans le rang qui leur convient,",40,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (80,"مِنْ نُقْطَةِ الْعِلْمِ اَوْ مِنْ شَكْلَةِ الْحِكَمِ","N’étant en comparaison de sa science, et au prix de sa sagesse, que ce qu'est un point ou un accent dans l'écriture. ",40,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (81,"فَهْوَ الَّذِي تَمَّ مَعْنَاهُ وَصُورَتُهُ","C'est lui qui est parfait par les qualités de son cœur et par les grâces de sa personne.",41,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (82,"ثُمَّ اصْطَفَاهُ حَبِيباً بَارِئُ النَّسَمِ","Le créateur des âmes l'a choisi pour ami. ",41,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (83,"مُنَزَّهٌ عَنْ شَرِيكٍ فِي مَحَاسِنِهِ","Il ne partage avec aucun autre ses qualités incomparables ;",42,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (84,"فَجَوْهَرُ الْحُسْنِ فِيهِ غَيْرُ مُنْقَسِمِ","Il possède toute entière et sans partage la substance même de l'excellence. ",42,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (85,"دَعْ مَا ادَّعَتْهُ النَّصَارَىٰ فِي نَبِيِّهِمُ","Laisse là ce que les chrétiens débitent faussement de leur prophète ",43,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (86,"وَاحْكُمْ بِمَا شِئْتَ مَدْحاً فِيهِ وَاحْتَكِمِ","Cela seul excepté [4], use d'une liberté sans bornes dans les éloges que tu donneras à Muhammad. ",43,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (87,"وَانْسُبْ إِلَىٰ ذَاتِهِ مَا شِئْتَ مِنْ شَرَفٍ","Vante autant qu'il te plaira l'excellence de sa nature, ",44,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (88,"وَانْسُبْ إِلَىٰ قَدْرِهِ مَا شِئْتَ مِنْ عِظَمِ","Relève autant que tu le voudras l'éminence de ses mérites ; ",44,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (89,"فَإِنَّ فَضْلَ رَسُولِ اللهِ لَيْسَ لَهُ","Car l'excellence de l'apôtre de Dieu ne connaît point de bornes,",45,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (90,"حَدٌّ فَيُعْرِبَ عَنْهُ نَاطِقٌ بِفَمِ","Et il n'est personne dont les paroles puissent dignement l'exprimer. ",45,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (91,"لَوْ نَاسَبَتْ قَدْرَهُ آيَاتُهُ عِظَماً","Si la grandeur de ses miracles répondait à l'éminence de son mérite,",46,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (92,"اَحْيَا اسْمُهُ حِينَ يُدْعَىٰ دَارِسَ الرِّمَمِ","La seule invocation de son nom rendrait la vie aux ossements depuis longtemps desséchés. ",46,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (93,"لَمْ يَمْتَحِنَّا بِمَا تَعْيَا الْعُقُولُ بِهِ","Par l'amour qu'il nous a porté, il n'a point voulu nous mettre à une épreuve dangereuse, en nous enseignant des choses auxquelles notre intelligence ne pût atteindre.",47,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (94,"حِرْصاً عَلَيْنَا فَلَمْ نَرْتَبْ وَلَمْ نَهِمِ","Nous n'avons éprouvé ni doute ni soupçon sur la vérité de sa doctrine. ",47,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (95,"اَعْيَا الْوَرَىٰ فَهْمُ مَعْنَاهُ فَلَيْسَ يُرَىٰ","Les hommes s'efforceraient en vain de comprendre l'excellence de ses qualités intérieures ;",48,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (96,"لِلْقُرْبِ وَالْبُعْدِ فِيهِ غَيْرُ مُنْفَحِمِ","Il n'en est aucun soit proche soit éloigné qui ne soit incapable d'y atteindre. ",48,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (97,"كَالشَّمْسِ تَظْهَرُ لِلْعَيْنَيْنِ مِنْ بُعُدٍ","Tel le soleil vu de loin ne paraît pas dans sa véritable grandeur, ",49,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (98,"صَغِيرَةً وَتُكِلُّ الطَّرْفَ مِن اَمَمِ","Et, regardé de près, éblouit la vue. ",49,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (99,"وَكَيْفَ يُدْرِكُ فِي الدُّنْيَا حَقِيقَتَهُ","Et comment pourraient, en ce monde, atteindre à la connaissance parfaite de ce qu'est ce grand prophète,",50,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (100,"قَوْمٌ نِيَامٌ تَسَلَّوْا عَنْهُ بِالْحُلُمِ","Des mortels plongés dans le sommeil, qui se contentent des songes de leur imagination ? ",50,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (101,"فَمَبْلَغُ الْعِلْمِ فِيهِ اَنَّهُ بَشَرٌ","Tout ce qu'on peut savoir de lui c'est qu'il est homme, ",51,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (102,"وَاَنَّهُ خَيْرُ خَلْقِ اللهِ كُلِّهِمِ","Et la plus excellente des créatures de Dieu. ",51,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (103,"وَكُلُّ آيٍ اَتَى الرُّسْلُ الْكِرَامُ بِهَا","Tous les miracles qu'ont faits les saints envoyés de Dieu, ",52,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (104,"فَإِنَّمَا اتَّصَلَتْ مِنْ نُورِهِ بِهِمِ","N’étaient qu'une communication de la lumière de ce prophète. ",52,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (105,"فَإِنَّهُ شَمْسُ فَضْلٍ هُمْ كَوَاكِبُهَا","Il est lui seul le soleil de l'excellence, les autres ne sont que les planètes qui dépendent de ce soleil,",53,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (106,"يُظْهِرْنَ اَنْوَارَهَا لِلنَّاسِ فِي الظُّلَمِ","Et qui réfléchissent ses rayons lumineux sur les mortels, au milieu des ténèbres. ",53,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (107,"اَكْرِمْ بخَلْقِ نَبِيٍّ زَانَهُ خُلُقٌ","Combien est digne d'admiration la figure de ce prophète, dont les charmes sont relevés par ses qualités intérieures,",54,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (108,"بِالْحُسنِ مُشْتَمِلٍ بِالْبِشْرِ مُتَّسِمِ","Qui réunit toutes les grâces, qui a pour caractère distinctif la douceur et l'aménité de ses traits. ",54,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (109,"كَالزَّهْرِ فِي تَرَفٍ وَالْبَدْرِ فِي شَرَفٍ","Il réunit à la beauté délicate d'une fleur, la grandeur majestueuse de la lune.",55,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (110,"وَالْبَحْرِ فِي كَرَمٍ وَالدَّهْرِ فِي هِمَمِ","Sa générosité est vaste comme la mer, ses desseins sont grands et fermes comme le temps. ",55,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (111,"كَأَنَّهُ وَهْوَ فَرْدٌ فِي جَلَالَتِهِ","Lors même qu'il est seul, la majesté de son visage rend son aspect aussi redoutable à ceux qui le rencontrent,",56,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (112,"فِي عَسْكَرٍ حِينَ تَلْقَاهُ وَفِي حَشَمِ","Que s'il avait autour de lui une armée et de nombreuses cohortes. ",56,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (113,"كَأَنَّمَا اللُّؤْلُؤُ الْمَكْنُونُ فِي صَدَفٍ","On dirait que les organes qui produisent en lui la parole et le sourire,",57,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (114,"مِنْ مَعْدِنَيْ مَنْطِقٍ مِنْهُ وَمُبْتَسَمِ","Sont des perles cachées au fond de la nacre. ",57,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (115,"لَا طِيبَ يَعْدِلُ تُرْباً ضَمَّ اَعْظُمَهُ","Aucun parfum n'égale l'odeur suave de la terre qui couvre ses os; ",58,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (116,"طُوبَىٰ لِمُنْتَشِقٍ مِنْهُ وَمُلْتَثِمِ","Heureux qui respire cette odeur, qui couvre cette terre de baisers! ",58,3);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (117,"اَبَانَ مَوْلِدُهُ عَنْ طِيبِ عُنْصُرِهِ","L'instant même de sa naissance a fait connaître l'excellence de son origine.",59,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (118,"يَا طِيبَ مُبتَدَإٍ مِنْهُ وَمُخْتَتَمِ","Qu'ils sont précieux les premiers et les derniers moments de son existence ! ",59,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (119,"يَوْمٌ تَفَرَّسَ فِيهِ الْفُرْسُ اَنَّهُمُ","En ce jour les Perses ont reconnu par des pronostics certains, ",60,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (120,"قَدْ أُنْذِرُوا بِحُلُولِ الْبُؤْسِ وَالنِّقَمِ","L’annonce des malheurs et de la vengeance qui allaient tomber sur eux. ",60,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (121,"وَبَاتَ إِيوَانُ كِسْرَىٰ وَهْوَ مُنْصَدِعٌ","Le portique de Chosroês renversé au milieu de la nuit annonça par sa chute la division ",61,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (122,"كَشَمْلِ اَصْحَابِ كِسْرَىٰ غَيْرَ مُلْتَئِمِ","Qui allait ruiner la famille des souverains de cet empire, sans aucun espoir de réunion. ",61,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (123,"وَالنَّارُ خامِدَةُ الْأَنْفَاسِ مِنْ اَسَفٍ","Le feu sacré, dans la douleur où le plongeait cet événement, vit s'éteindre sa flamme,",62,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (124,"عَلَيْهِ وَالنَّهْرُ سَاهِي الْعَيْنِ مِنْ سَدَمِ","Et le fleuve, troublé par la frayeur, oublia sa source accoutumée. ",62,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (125,"وَسَاءَ سَاوَةَ اَنْ غَاضَتْ بُحَيْرَتُهَا","Sava [5] s'affligea sur la disparition de ses eaux que la terre avait englouties,",63,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (126,"وَرُدَّ وَارِدُهَا بِالْغَيْظِ حِينَ ظَمِي","Et celui qui venait y étancher sa soif s'en retourna, transporté de colère et d'indignation. ",63,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (127,"كَأَنَّ بِالنَّارِ مَا بِالْمَاءِ مِنْ بَلَلٍ","Il semblait qu'en ce jour la violence de l'affliction eût transporté au feu l'humidité naturelle à l'élément aqueux,",64,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (128,"حُزْناً وَبِالْمَاءِ مَا بِالنَّارِ مِنْ ضَرَمِ","Et à l'eau l'ardeur desséchante du feu. ",64,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (129,"وَالْجِنُّ تَهْتِفُ وَالْأَنْوَارُ سَاطِعَةٌ","Alors les génies poussèrent des hurlements, des lumières éclatantes s'élevèrent et se répandirent dans l'atmosphère,",65,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (130,"وَالْحَقُّ يَظْهَرُ مِنْ مَعْنىً وَمِنْ كَلِمِ","La vérité se manifesta par des signes muets et par des paroles. ",65,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (131,"عَمُوا وَصَمُّوا فَإِعْلَانُ الْبَشَائِرِ لَمْ","Mais ils ont été aveugles et sourds [6] les impies : les annonces les plus claires des heureux événements qui allaient arriver,",66,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (132,"تُسْمَعْ وَبَارِقَةُ الْإِنْذَارِ لَمْ تُشَمِ","Ils ne les ont point entendues ; les signes les plus éclatants des maux dont le ciel les menaçait, ils n'y ont point fait attention. ",66,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (133,"مِنْ بَعْدِ مَا اَخْبَرَ الْأَقْوَامَ كَاهِنُهُمْ","Après même que les peuples ont été avertis par leurs devins ",67,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (134,"بِأَنَّ دِينَهُمُ الْمُعْوَجَّ لَمْ يَقُمِ","Que leurs religions erronées allaient, être détruites ; ",67,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (135,"وَبَعْدَ مَا عَايَنُوا فِي الْأُفْقِ مِنْ شُهُبٍ","Après qu'ils ont vu dans les cieux des flammes se détacher et se précipiter en bas,",68,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (136,"مُنْقَضَّةٍ وَّفْقَ مَا فِي الْأَرْضِ مِنْ صَنَمِ","De même que sur la terre leurs idoles se renversaient. ",68,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (137,"حَتَّىٰ غَدَا عَنْ طَرِيقِ الْوَحْيِ مُنْهَزِمٌ","Poursuivis par ces flammes, les démons prirent la fuite à l'envi les uns des autres,",69,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (138,"مِنَ الشَّيَاطِينِ يَقْفُو إِثْرَ مُنْهَزِمِ","Obligés d'abandonner la route céleste par laquelle la révélation se communique aux mortels. ",69,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (139,"كَأَنَّهُمْ هَرَباً اَبْطَالُ اَبْرَهَةٍ","A voir leur fuite précipitée, on eût dit, que c'étaient les guerriers de l'armée d’Abraha [7] ",70,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (140,"اَوْ عَسْكَرٌ بِالْحَصَىٰ مِنْ رَاحَتَيْهِ رُمِي","Ou les troupes infidèles mises en fuite par les cailloux que lancèrent sur elles les mains du Prophète à la journée de Badr [8] ",70,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (141,"نَبْذاً بِهِ بَعْدَ تَسْبِيحٍ بِبَطْنِهِمَا","Lorsque ces cailloux, après avoir chanté les louanges de Dieu dans ses mains, furent lancés contre l'ennemi,",71,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (142,"نَبْذَ الْمُسَبِّحِ مِنْ اَحْشَاءِ مُلْتَقِمِ","Semblables à Jonas jeté hors des entrailles du monstre qui l'avait dévoré, après que, dans son sein, il avait invoqué le nom de Dieu. ",71,4);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (143,"جَاءَتْ لِدَعْوَتِهِ الْأَشْجَارُ سَاجِدَةً","A l'ordre de Muhammad, les arbres sont venus se prosterner devant lui ;",72,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (144,"تَمْشِي إِلَيْهِ عَلَىٰ سَاقٍ بِلَا قَدَمِ","Sans pieds et portés seulement sur leur tige, ils s'avançaient vers le Prophète. ",72,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (145,"كَأَنَّمَ سَطَّرَتْ سَطْراً لِمَا كَتَبَتْ","De même que le crayon trace sur le papier la ligne qui doit servir de règle à l'écrivain,",73,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (146,"فُرُوعُهَا مِنْ بَدِيعِ الْخَطِّ فِي اللَّقَمِ","Ainsi leur tronc semblait en marchant décrire une ligne droite, sur laquelle leurs branches, en sillonnant la poussière, devaient tracer au milieu de la route une écriture merveilleuse. ",73,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (147,"مِثْلَ الْغَمَامَةِ اَنَّىٰ سَارَ سَائِرَةٌ","Semblables dans leur obéissance à ce nuage officieux qui suivait l'apôtre de Dieu en quelque endroit qu'il portât ses pas,",74,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (148,"تَقِيهِ حَرَّ وَطِيسٍ لِلْهَجِيرِ حَمِي","Pour le défendre des feux du soleil dans la plus grande chaleur du jour. ",74,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (149,"اَقْسَمْتُ بِالْقَمَرِ الْمُنْشَقِّ إنَّ لَهُ","J'en jure par la lune qui, à son ordre, se fendit en deux ; le prodige qui s'opéra alors sur cet astre,",75,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (150,"مِنْ قَلْبِهِ نِسْبَةً مَبْرُورَةَ الْقَسَمِ","Est pareil à celui qui s'était opéré sur le cœur du Prophète lorsque les anges l'avaient ouvert pour le purifier [9] et cette ressemblance est si parfaite que l'on peut légitimement l'assurer avec serment. ",75,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (151,"وَمَا حَوَى الْغَارُ مِنْ خَيْرٍ وَمِنْ كَرَمٍ","Les yeux des incrédules frappés d'aveuglement",76,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (152,"وَكُلُّ طَرْفٍ مِنَ الْكُفَّارِ عَنْهُ عَمِي","N’ont point vu ce que la caverne renfermait de vertus et de mérites. [10] ",76,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (153,"فَالصِّدْقُ فِي الْغَارِ وَالصَّدِّيقُ لَمْ يَرِمَا","La justice même et l'ami fidèle [11] étaient cachés dans la caverne sans que personne ne les aperçût,",77,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (154,"وَهُمْ يَقُولُونَ مَا بِالْغَارِ مِنْ اَرِمِ","Et les impies disaient : Assurément il n'y a personne dans cette caverne. ",77,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (155,"ظَنُّوا الْحَمَامَ وَظَنُّوا الْعَنْكَبُوتَ عَلَىٰ","Ils ne s'imaginaient pas que des colombes voltigeassent autour de la créature la plus excellente,",78,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (156,"خيْرِ الْبَرِّيَّةِ لَمْ تَنْسُجْ وَلَمْ تَحُمِ","Et qu'une araignée la couvrit de sa toile. ",78,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (157,"وِقَايَةُ اللهِ اَغْنَتْ عَنْ مُضَاعَفَةٍ","La protection de Dieu lui a tenu lieu de la cotte de mailles la plus épaisse,",79,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (158,"مِنَ الدُّرُوعِ وَعَنْ عَالٍ مِنَ الْأُطُمِ","Et de la forteresse la plus inaccessible. ",79,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (159,"مَا سَامَنِي الدَّهْرُ ضَيماً وَاسْتَجَرْتُ بِهِ","Jamais, dans les injustices que j'ai éprouvées de la fortune, je n'ai eu recours à l'assistance de Muhammad,",80,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (160,"إِلَّا وَنِلْتُ جِوَاراً مِنْهُ لَمْ يُضَمِ","Que je n'aie trouvé en lui un patron dont la protection est invincible. ",80,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (161,"وَلَا الْتَمَسْتُ غِنَى الدَّارَيْنِ مِنْ يَدِهِ","Jamais je n'ai désiré recevoir de sa main aucun bien temporel pu spirituel,",81,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (162,"إِلَّا اسْتَلَمْتُ النَّدَىٰ مِنْ خَيْرِ مُسْتَلَمِ","Que cette main, la plus excellente que l’on puisse baiser, ne m'ait accordé quelque don de sa libéralité. ",81,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (163,"لَا تُنْكِرِ الْوَحْيَ مِنْ رُؤْيَاهُ إِنَّ لَهُ","Ne fais aucune difficulté de reconnaître sa vision nocturne [12] pour une véritable révélation ;",82,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (164,"قَلْباً إِذَا نَامَتِ الْعَيْنَانِ لَمْ يَنَمِ","Car le cœur de ce Prophète ne dort pas, lors même que ses yeux sont fermés par le sommeil. ",82,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (165,"وَذَاكَ حِينَ بُلُوغٍ مِنْ نُبُوَّتِهِ","Dès lors il avait atteint l'âge parfait pour la mission prophétique, ",83,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (166,"فَلَيْسَ يُنْكَرُ فِيهِ حالُ مُحْتَلِمِ","Et l'on ne doit lui refuser aucun des avantages qui conviennent à l'âge parfait. ",83,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (167,"تَبَارَكَ اللهُ مَا وَحْيٌ بِمُكْتَسَبٍ","AAAA",84,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (168,"وَلَا نَبِيٌّ عَلَىٰ غَيْبٍ بِمُتَّهَمِ","AAAA",84,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (169,"كَمْ اَبْرَاَتْ وَصِباً بِاللَّمْسِ رَاحَتُهُ","Combien de maladies a guéries le seul attouchement de sa main! ",85,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (170,"وَاَطْلَقَتْ اَرِباً مِنْ رِبْقَةِ اللَّمَمِ","Combien de malheureux elle a délivrés des mains de la folie ! ",85,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (171,"وَاَحْيَتِ السَّنَةَ الشَّهْبَاءَ دَعْوَتُهُ","Vivifiée par l'efficacité de ses prières, l'année de la plus grande sécheresse s'est distinguée au milieu des temps de disette,",86,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (172,"حَتَّىٰ حَكَتْ غُرَّةً فِي الْأَعْصُرِ الدُّهُمِ","Par une abondante fertilité, semblable à cette étoile blanche qui brille sur le front d'un cheval, au milieu des crins noirs qui l'environnent de toute part. ",86,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (173,"بِعَارِضٍ جَادَ اَوْ خِلْتَ الْبِطَاحَ بِهَا","Les nuages l'ont fécondée par leurs eaux abondantes, ",87,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (174,"سَيْباً مِنَ الْيَمِّ اَوْ سَيْلاً مِنَ الْعَرِمِ","Et l'on eût dit que les vallées étaient devenues un bras de mer, ou des torrents échappés de leurs digues. ",87,5);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (175,"دَعْنِي وَوَصْفِيَ آيَاتٍ لَهُ ظَهَرَتْ","Laisse-moi, que je chante les oracles [13] de ce Prophète, ils ont paru ces oracles avec un éclat,",88,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (176,"ظُهُورَ نَارِ الْقِرَىٰ لَيْلاً عَلىٰ عَلَمِ","Pareil à celui que jettent, au milieu de la nuit et sur le sommet d'une montagne, les feux qu'allume une main généreuse pour attirer le voyageur dans sa demeure hospitalière. ",88,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (177,"فَالدُّرُّ يَزْدَادُ حُسْناً وَهْوَ مُنْتَظِمٌ","La perle reçoit, il est vrai, quelque augmentation de beauté de la main habile qui l'emploie à former un collier ;",89,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (178,"وَلَيْسَ يَنْقُصُ قَدْراً غَيْرَ مُنْتَظِمِ","Mais lors même qu'elle n'est pas mise en œuvre, elle ne perd rien de son prix. ",89,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (179,"فَمَا تَطَاوَلُ آمَالُ الْمَدِيحِ إِلَىٰ","Pour moi je n'espère pas de pouvoir atteindre dans mes chants ",90,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (180,"مَا فِيهِ مِنْ كَرَمِ الْأَخْلَاقِ وَالشِّيَمِ","L’excellence des vertus et des qualités naturelles de cet auguste envoyé du Très-Haut. ",90,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (181,"آيَاتُ حَقٍّ مِنَ الرَّحْمَـٰنِ مُحْدَثَةٌ","Ces oracles, oracles de la vérité, émanés du Dieu de miséricorde, ont été produits dans le temps;[14]",91,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (182,"قَدِيمَةٌ صِفَةُ الْمَوْصُوفِ بِالْقِدَمِ","Mais en tant qu'ils sont un attribut de celui dont l'essence est éternelle, ils sont eux-mêmes aussi anciens que l'éternité, ",91,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (183,"لَمْ تَقْتَرِنْ بِزَمَانٍ وَهْيَ تُخْبِرُنَا","Sans qu'on puisse leur assigner aucune époque ; ils nous instruisent cependant et de ce qui doit arriver au dernier jour,",92,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (184,"عَنِ الْمَعَادِ وَعَنْ عَادٍ وَعَنْ إِرَمِ","Et des événements des siècles d’Âd [15] et d'Irem [16] ",92,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (185,"دَامَتْ لَدَيْنَا فَفَاقَتْ كُلَّ مُعْجِزَةٍ","Ils sont un miracle toujours existant près de nous, bien supérieurs en cela aux miracles",93,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (186,"مِنَ النَّبِيِّينَ إِذْ جاءَتْ وَلَمْ تَدُمِ","Des autres prophètes dont l'existence n'a été que d'un instant. ",93,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (187,"مُحَكَّمَاتٌ فَمَا تُبْقِينَ مِنْ شُبَهٍ","Leur sens clair ne laisse aucun doute dont puissent abuser ceux qui se séparent de la vérité,",94,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (188,"لِذِي شِقَاقٍ وَلَا يَبْغِينَ مِنْ حَكَمِ","Et il n'est pas besoin d'arbitre pour fixer leur signification. ",94,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (189,"مَا حُورِبَتْ قَطُّ إِلَّا عَادَ مِنْ حَرَبٍ","Jamais ils n'ont éprouvé d'attaque,",95,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (190,"اَعْدَى الْأَعَادِي إِلَيْهَا مُلْقِيَ السَّلَمِ","Que l'ennemi le plus envenimé n'ait abandonné le combat pour leur faire des propositions de paix. ",95,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (191,"رَدَّتْ بَلَاغَتُهَا دَعْوَىٰ مُعَارِضِهَا","Leur sublime éloquence repousse toutes les entreprises de quiconque ose les attaquer,",96,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (192,"رَدَّ الْغَيُورِ يَدَ الْجَانِي عَنِ الْحَرَمِ","Comme un homme jaloux repousse la main téméraire qui veut attenter à l'honneur de ses femmes. ",96,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (193,"لَهَا مَعَانٍ كَمَوْجِ الْبَحْرِ فِي مَدَدٍ","L'abondance des sens qu'ils renferment est pareille aux flots de la mer ;",97,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (194,"وَفَوْقَ جَوْهَرِهِ فِي الْحُسْنِ وَالْقِيَمِ","Ils surpassent en prix et en beauté les perles que recèle l'Océan. ",97,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (195,"فَمَا تُعَدُّ وَلَا تُحْصَىٰ عَجَائِبُهَا","Les merveilles qu'on y découvre ne sauraient être comptées ; ",98,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (196,"وَلَا تُسَامُ عَلَى الْإِكْثَارِ بِالسَّأَمِ","Quoiqu’on les relise souvent, jamais ils ne causent de dégoût. ",98,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (197,"قَرَّتْ بِهَا عَيْنُ قَارِيهَا فَقُلْتُ لَهُ","Ils répandent la joie et la vie sur les yeux de quiconque les lit :",99,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (198,"لَقَدْ ظَفِرْتَ بِحَبْلِ اللهِ فَاعْتَصِمِ","Ô toi qui jouis de ce bonheur, tu as saisi une corde qui est Dieu même, garde-toi de la laisser échapper de tes mains. ",99,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (199,"إِنْ تَتْلُهَا خِيفَةً مِنْ حَرِّ نَارِ لَظَىٰ","Si tu les lis pour y trouver un refuge contre les ardeurs du feu de l'enfer,",100,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (200,"اَطْفَأْتَ حَرَّ لَظَىٰ مِنْ وِرْدِهَا الشَّبِمِ","Les eaux fraîches du livre sacré éteindront les flammes infernales. ",100,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (201,"كَأَنَّهَا الْحَوضُ تَبْيَضُّ الْوُجُوهُ بِهِ","Ainsi le bassin du Prophète [17] blanchira le visage des pécheurs,",101,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (202,"مِنَ الْعُصَاةِ وَقَدْ جَاؤُوهُ كَالْحُمَمِ"," Fussent-ils noirs comme le charbon avant de se plonger dans ses eaux. ",101,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (203,"وَكَالصِّرَاطِ وَكَالْمِيزَانِ مَعْدِلَةً","Droits comme le pont Sirath [18] justes comme la balance dans laquelle seront pesées les œuvres des mortels,",102,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (204,"فَالْقِسْطُ مِنْ غَيْرِهَا فِي النَّاسِ لَمْ يَقُمِ","Eux seuls sont la règle et la source unique de toute justice parmi les hommes. ",102,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (205,"لَا تَعْجَبَنْ لِحَسُودٍ رَاحَ يُنْكِرُهَا","Ne t'étonne pas que l'envieux méconnaisse leur mérite,",103,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (206,"تَجَاهُلاً وَهْوَ عَيْنُ الْحَاذِقِ الْفَهِمِ","Agissant ainsi en insensé, quoiqu'il soit plein de discernement et d'intelligence ",103,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (207,"قَدْ تُنْكِرُ الْعَيْنُ ضَوْءَ الشَّمْسِ مِنْ رَمَدٍ","Ne vois-tu pas que l'œil altéré méconnaît l'éclat du soleil,",104,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (208,"وَيُنْكِرُ الْفَمُ طَعْمَ الْمَاءِ مِنْ سَقَمِ","Et que la bouche d'un malade ne reconnaît plus la saveur de l'eau? ",104,6);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (209,"يَا خَيْرَ مَنْ يَمَّمَ الْعَافُونَ سَاحَتَهُ","O toi, le plus excellent de tous ceux dont les indigents visitent la cour [19] ",105,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (210,"سَعْياً وَفَوْقَ مُتُونِ الْأَيْنُقِ الرُّسُمِ","Vers lequel ils se rendent en foule soit à pied, soit sur le dos d'un chameau dont les pieds impriment de profondes traces sur la poussière ",105,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (211,"وَمَنْ هُوَ الْآيَةُ الْكُبْرَىٰ لِمُعتَبِرٍ","Toi, le plus grand de tous les prodiges pour l'homme capable de réflexion,",106,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (212,"وَمَنْ هُوَ النِّعمَةُ الْعُظمَىٰ لِمُغْتَنِمِ","Le plus précieux bienfait de la divinité pour quiconque sait le mettre à profit ! ",106,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (213,"سَرَيْتَ مِنْ حَرَمٍ لَيْلاًإِلَىٰ حَرَمٍ","En une seule nuit tu as été transporté du sanctuaire de la Mecque au sanctuaire de Jérusalem",107,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (214,"كَمَا سَرَى الْبَدْرُ فِي دَاجٍ مِنَ الظُّلَمِ","Ainsi la lune parcourt la voûte céleste au milieu des plus épaisses ténèbres. ",107,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (215,"وَبِتَّ تَرْقَىٰ إِلَىٰ اَنْ نِلْتَ مَنْزِلَةً","Tu n'as cessé de t'élever jusqu'à ce que tu aies atteint un degré auquel nul mortel ne saurait prétendre",108,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (216,"مِنْ قَابَ قَوْسَيْنِ لَمْ تُدْرَكْ وَلَمْ تُرَمِ","La longueur de deux arcs seulement te séparait de la divinité [20] ",108,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (217,"وَقَدَّمَتْكَ جَمِيعُ الْأَنْبِيَاءِ بِهَا","Tous les prophètes, tous les envoyés de Dieu ont reconnu ta supériorité ;",109,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (218,"وَالرُّسْلِ تَقْدِيمَ مَخْدُومٍ عَلَىٰ خَدَمِ","Ils t'ont cédé le pas, comme le serviteur se tient derrière son maître. ",109,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (219,"وَاَنْتَ تَخْتَرِقُ السَّبْعَ الطِّبَاقَ بِهِمْ","Entouré de cette vénérable cohorte parmi laquelle tu paraissais comme le porte-enseigne,",110,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (220,"فِي مَوْكِبٍ كُنْتَ فِيهِ صَاحِبَ الْعَلَمِ","Tu as traversé l'espace des sept cieux, ",110,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (221,"حَتَّىٰ إِذَا لَمْ تَدَعْ شَأْواً لِمُسْتَبِقٍ","Ne laissant devant toi aucune place plus proche de la divinité, ",111,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (222,"مِنَ الدُّنُوِّ وَلَا مَرْقىً لِمُسْتَنِمِ","Au-dessus de toi aucun degré plus élevé que celui où tu es parvenu. ",111,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (223,"خَفَضْتَ كُلَّ مَقَامٍ بِالْإِضَافَةِ إِذْ","Tu as rendu tout autre rang vil et méprisable,",112,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (224,"نُودِيتَ بِالرَّفْعِ مِثْلَ الْمُفْرَدِ الْعَلَمِ","En comparaison de celui que tu occupais lorsque Dieu lui-même t'a appelé par ton nom, comme on appelle celui qui est distingué par son mérite, ",112,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (225,"كَيْمَا تَفُوزَ بِوَصْلٍ اَيِّ مُسْتَتِرٍ","Et qu'il t'a invité à venir jouir de l'union la plus inaccessible aux regards des mortels,",113,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (226,"عَنِ الْعُيُونِ وَسِرٍّ اَيِّ مُكْتَتِمِ","Et de la vue du secret le plus impénétrable. ",113,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (227,"فَحُزْتَ كُلَّ فِخَارٍ غَيْرَ مُشْتَرَكٍ","Tu as réuni toute sorte de gloire en ta personne, sans la partager avec qui que ce soit.",114,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (228,"وَجُزْتَ كُلَّ مَقَامٍ غَيْرَ مُزْدَحَمِ","Il n'est aucun lieu que tu n'aies traversé, sans y trouver de concurrent. ",114,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (229,"وَجَلَّ مِقْدَارُ مَا وُلِّيتَ مِنْ رُتَبٍ","Sublime degré que celui auquel tu as été élevé !",115,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (230,"وَعَزَّ إِدْرَاكُ مَا أُولِيتَ مِنْ نِعَمِ"," Éminentes faveurs que celles dont tu as été comblé ! ",115,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (231,"بُشْرَىٰ لَنَا مَعْشَرَ الْإِسْلَامِ إِنَّ لَنَا","Disciples de l'islamisme, que notre sort est heureux !",116,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (232,"مِنَ الْعِنَايَةِ رُكْناً غَيْرَ مُنْهَدِمِ","Nous avons, dans la protection de Dieu même, une ferme colonne que rien ne peut renverser. ",116,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (233,"لَمَّا دَعَى اللهُ دَاعِينَا لِطَاعَتِهِ","Celui qui nous a appelés au culte de Dieu a été déclaré par Dieu même le plus excellent des envoyés :",117,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (234,"بِأَكْرَمِ الرُّسْلِ كُنَّا اَكْرَمَ الْأُمَمِ","Nous sommes donc aussi le plus excellent de tous les peuples. ",117,7);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (235,"رَاعَتْ قُلُوبَ الْعِدَا اَنْبَاءُ بِعْثَتِهِ","La seule nouvelle de sa mission a jeté l'épouvante dans le cœur de ses ennemis :",118,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (236,"كَنَبْأَةٍ اَجْفَلَتْ غُفْلاً مِنَ الْغَنَمِ","Tel un troupeau d'imbéciles brebis fuit en désordre au seul rugissement du lion. ",118,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (237,"مَا زَالَ يَلْقَاهُمُ فِي كُلِّ مُعْتَرَكٍ","Partout où il a repoussé leurs attaques, il les a laissés percés de ses lances et étendus sur le champ de bataille,",119,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (238,"حَتَّىٰ حَكَوْا بِالْقَنَا لَحْماً عَلَىٰ وَضَمِ","Comme la viande sur l'étal d'un boucher. ",119,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (239,"وَدُّوا الْفِرَارَ فَكَادُوا يَغْبِطُونَ بِهِ","La fuite a été l'objet de leurs vœux,",120,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (240,"اَشْلَاءَ شَالَتْ مَعَ الْعُقْبَانِ وَالرَّخَمِ","Ils portaient envie à ceux dont les membres déchirés étaient enlevés en l'air par les aigles et les vautours. ",120,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (241,"تَمْضِي اللَّيَالِي وَلَا يَدْرُونَ عِدَّتَهَا","Les jours et les nuits se succédaient et s'écoulaient sans que l'effroi dont ils étaient saisis leur permit d'en connaître le nombre,",121,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (242,"مَا لَمْ تَكُنْ مِنْ لَّيَالِي الْأَشْهُرِ الْحُرُمِ","À l'exception des mois sacrés où la guerre est suspendue [21] ",121,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (243,"كَأَنَّمَا الدِّينُ ضَيْفٌ حَلَّ سَاحَتَهُمْ","La religion était pour eux comme un hôte importun descendu dans leur demeure,",122,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (244,"بِكُلِّ قَرْمٍ إِلَىٰ لَحْمِ الْعِدَا قَرِمِ","Suivi d'une foule de braves tous altérés du sang de leurs ennemis, ",122,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (245,"يَجُرُّ بَحْرَ خَمِيسٍ فَوْقَ سَابِحَةٍ","Traînant après lui une mer de combattants montés sur d'agiles coursiers, ",123,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (246,"يَرْمِي بِمَوجٍ مِنَ الْأَبْطَالِ مُلْتَطِمِ","Une mer qui vomissait des flots de guerriers dont les rangs pressés se choquaient et se heurtaient à l'envi, ",123,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (247,"مِنْ كُلِّ مُنْتَدِبٍ للهِ مُحْتَسِبٍ","Tous dociles à la voix de Dieu, tous animés par l'espoir de ses récompenses,",124,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (248,"يَسْطُو بِمُسْتَأْصِلٍ لِلْكُفْرِ مُصْطَلِمِ","Enflammés du désir d'extirper et d'anéantir l'impiété. ",124,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (249,"حَتَّىٰ غَدَتْ مِلَّةُ الْإِسْلَامِ وَهْيَ بِهِمْ","La religion musulmane qui était d'abord comme étrangère parmi eux, et l'objet de leur mépris, est, pour ainsi dire,",125,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (250,"مِنْ بَعْدِ غُرْبَتِهَا مَوْصُولَةَ الرَّحِمِ","Devenue par l'effet des armes victorieuses de ce grand Prophète, leur proche parente, et le plus cher objet de leur amour. ",125,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (251,"مَكْفُولَةً اَبَداً مِنْهُمْ بِخَيْرِ اَبٍ","Dieu a assuré pour toujours parmi eux le secours d'un père et les soins attentifs d'un époux à cette religion auguste ;",126,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (252,"وَخَيْرِ بَعْلٍ فَلَمْ تَيْتَمْ وَلَمْ تَئِمِ","Jamais elle n'a éprouvé le triste sort de l'orphelin, ou l'abandon du veuvage. ",126,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (253,"هُمُ الْجِبَالُ فَسَلْ عَنْهُم مُّصَادِمَهُمْ","Ces défenseurs de la religion ont été aussi fermes et aussi inébranlables que des montagnes.",127,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (254,"مَاذَا رَأَوْا مِنْهُمُ فِي كُلِّ مُصْطَدَمِ","Demande à leurs adversaires ce qu'ils ont éprouvé de la part de ces braves dans chacun des lieux qui ont été le théâtre de leur courage. ",127,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (255,"وَسَلْ حُنَيْناً وَسَلْ بَدْراً وَسَلْ أُحُداً","Interroge Honeïn, Badr et Ohod [22]",128,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (256,"فُصُولَ حَتْفٍ لَهُمْ اَدْهَىٰ مِنَ الْوَخَمِ","Ces lieux où les ennemis de la religion ont succombé à un fléau mortel plus terrible que la peste. ",128,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (257,"اَلْمُصْدِرِي الْبِيضِ حُمْراً بَعْدَ مَا وَرَدَتْ","Les glaives de ces soutiens de l'islamisme qui, avant le combat, étaient d'une blancheur éclatante,",129,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (258,"مِنَ الْعِدَا كُلَّ مُسْوَدٍّ مِنَ اللِّمَمِ","Sont sortis rouges de l'action, après s'être abreuvés dans la gorge de leurs ennemis qu'ombrageait une épaisse forêt de cheveux. ",129,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (259,"وَالْكاَتِبِينَ بِسُمْرِ الْخَطِّ مَا تَرَكَتْ","Les flèches que distinguent des raies noires et dont Alkhatt [23]",130,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (260,"اَقْلَامُهُمْ حَرْفَ جِسْمٍ غَيْرَ مُنْعَجِمِ","A armé leurs mains, ont tracé une écriture profonde sur les corps de leurs adversaires ; ",130,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (261,"شَاكِي السِّلَاحِ لَهُمْ سِيمَىٰ تُمَيِّزُهُمْ","Ces nobles combattants, hérissés de leurs armes, ont un caractère de piété qui les distingue de leurs ennemis :",131,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (262,"وَالْوَرْدُ يَمْتَازُ بِالسِّيمَا مِنَ السَّلَمِ","Ainsi le rosier se distingue par ses épines, du bois de sélam qui n'est bon qu'à être la pâture du feu. ",131,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (263,"تُهْدِي إِلَيْكَ رِيَاحُ النَّصْرِ نَشْرَهُمُ","Les vents qui t'apportent leur odeur, sont les garants d'une victoire assurée :",132,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (264,"فَتَحْسَبُ الزَّهْرَ فِي الْأَكْمَامِ كُلَّ كَمِي","Chacun de ces guerriers, au milieu des armes qui le couvrent, semble une fleur au milieu de son calice. ",132,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (265,"كَأَنَّهُمْ في ظُهُورِ الْخَيْلِ نَبْتُ رُباً","Fixés sur le dos de leurs coursiers ; ils y demeurent aussi immobiles qu'une plante qui a crû sur une colline :",133,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (266,"مِنْ شِدَّةِ الْحَزْمِ لَا مِنْ شَدَّةِ الْحُزُمِ","C’est la fermeté de leur cœur qui les attache, et non la solidité de leurs sangles. ",133,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (267,"طَارَتْ قُلُوبُ الْعِدَا مِنْ بَأْسِهِمْ فَرَقاً","Leurs ennemis saisis d'effroi, perdent l'usage de la raison ;",134,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (268,"فَمَا تُفَرِّقَ بَيْنَ الْبَهْمِ وَالْبُهَمِ","Ils ne sont plus capables de distinguer un troupeau de faibles agneaux, d'un escadron de cavalerie. ",134,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (269,"وَمَنْ تَكُنْ بِرَسُولِ اللهِ نُصْرَتُهُ","Quiconque a pour appui l'assistance de l'apôtre de Dieu,",135,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (270,"إِنْ تَلْقَهُ الْأُسْدُ فِي آجَامِهَا تَجِمِ","Réduira au silence les lions mêmes dans les marais qui leur servent de retraite. ",135,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (271,"وَلَنْ تَرَىٰ مِنْ وَلِيٍّ غَيْرَ مُنْتَصِرٍ","Jamais vous ne verrez aucun de ses amis privé de la victoire, ",136,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (272,"بِهِ وَلَا مِن عَدُوٍّ غَيْرَ مُنْقَسِمِ","Ni aucun de ses ennemis qui ne soit vaincu. ",136,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (273,"اَحَلَّ أُمَّتَهُ فِي حِرْزِ مِلَّتِهِ","Il a assuré à son peuple, dans la forteresse de la religion, une demeure tranquille,",137,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (274,"كَاللَّيْثِ حَلَّ مَعَ الْأَشْبَالِ فِي اَجَمِ","Comme le lion habite sans crainte avec ses lionceaux dans des marais inaccessibles. ",137,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (275,"كَمْ جَدَّلَتْ كَلِمَاتُ اللهِ مِنْ جَدِلٍ","Combien de disputeurs audacieux que, par le ministère de ce prophète,",138,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (276,"فِيهِ وَكَم خَصَّمَ الْبُرهَانُ مِنْ خَصِمِ","Les paroles de Dieu ont terrassés ? Combien d'adversaires ont été subjugués par ses arguments victorieux ? ",138,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (277,"كَفَاكَ بِالْعِلْمِ فِي الْأُمِّيِّ مُعْجِزَةً","Te faut-il un autre prodige qu'une science si vaste dans un homme sans lettres,",139,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (278,"فِي الْجَاهِلِيَّةِ وَالتَّأْدِيبِ فِي الْيُتُمِ","Au milieu des siècles de l'ignorance, que tant de connaissances dans un orphelin ? ",139,8);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (279,"خَدَمْتُهُ بِمَدِيحٍ اَسْتَقِيلُ بِهِ","En lui offrant ce tribut de louanges, je me flatte d'obtenir la rémission des péchés",140,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (280,"ذُنُوبَ عُمْرٍ مَضَىٰ فِي الشِّعْرِ وَالْخِدَمِ","D’une vie passée dans les frivolités de la poésie et dans le service des grands. ",140,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (281,"إِذْ قَلَّدَانِيَ مَا تُخْشَىٰ عَوَاقِبُهُ","Ces vaines occupations ont orné mon cou d'une félicité passagère ",141,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (282,"كَأَنَّنِي بِهِمَا هَدْيٌ مِنَ النَّعَمِ","Dont les suites fâcheuses sont le sujet de mes justes alarmes : ainsi l'on pare une brebis destinée à servir de victime. ",141,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (283,"اَطَعْتُ غَيَّ الصِّبَا فِي الْحَالَتَيْنِ وَمَا","En me livrant à ces frivoles amusements j'ai suivi la séduction de la jeunesse ;",142,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (284,"حَصَلْتُ إِلَّا عْلَى الْآثَامِ وَالنَّدَمِ","Le crime et le repentir, voilà les fruits que j'en ai recueillis. ",142,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (285,"فَيَا خَسَارَةَ نَفْسٍ فِي تِجَارَتِهَا ","O mon âme ! Ton négoce t'a ruinée entièrement ;",143,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (286,"لَمْ تَشْتَرِ الدِّينَ بِالدُّنْيَا وَلَمْ تَسُمِ","Tu n'as pas su acheter les biens de la religion au prix des choses de ce monde. ",143,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (287,"وَمَنْ يَبِعْ آجِلاً مِنْهُ بِعَاجِلِهِ","Celui qui vend sa félicité future pour s'assurer un bonheur présent, ",144,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (288,"يَبِنْ لَهُ الْغَبْنُ فِي بَيْعٍ وَفِي سَلَمِ","Fait un échange funeste, et souffre une perte incalculable. ",144,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (289,"إِنْ آتِ ذَنْباً فَمَا عَهْدِي بِمُنْتَقِضٍ ","Quand je commettrais une faute, je ne perdrais pas pour cela tous mes droits à la protection de ce prophète :",145,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (290,"مِنَ النَّبِيِّ وَلَا حَبْلِي بِمُنْصَرِمِ","La corde à laquelle je me suis attaché, ne sera pas rompue sans ressource. ",145,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (291,"فَإِنَّ لِي ذِمَّةً مِنْهُ بِتَسْمِيَتِي","J'ai droit à le regarder comme mon patron, puisque je porte le nom de Muhammad ;",146,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (292,"مُحمَّدَاً وَهْوَ اَوْفَى الْخَلْقِ بِالذِّمَمِ","Et personne ne respecte plus que lui les droits de la clientèle. ",146,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (293,"إِنْ لَمْ يَكُنْ فِي مَعَادِي آخِذاً بِيَدِي","Si, au jour de la résurrection, il ne me prend pas la main avec une bonté pleine de tendresse,",147,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (294,"فَضْلاً وَإِلَّا فَقُلْ يَا زَلَّةَ الْقَدَمِ","Tu pourras dire de moi que j'avais appuyé les pieds sur un lieu glissant ; ",147,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (295,"حَاشَاهُ اَنْ يَحْرِمَ الرَّاجِي مَكَارِمَهُ","Mais loin de lui cette infidélité que quiconque a espéré en sa bonté, soit frustré de son espoir ;",148,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (296,"اَوْ يَرْجِعَ الْجَارُ مِنْهُ غَيْرَ مُحْتَرَمِ","Que celui qui a cherché un asile près, de lui, n'éprouve pas les effets de sa protection ! ",148,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (297,"ومُنْذُ اَلزَمْتُ اَفْكَارِي مَدَائِحَهُ","Depuis que mon esprit s'occupe de chanter ses louanges, ",149,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (298,"وَجَدْتُهُ لِخَلَاصِي خَيْرَ مُلْتَزِمِ","J’ai reconnu qu'il prend le soin le plus tendre de mon salut. ",149,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (299,"وَلَنْ يَفُوتَ الْغِنَىٰ مِنْهُ يَداً تَرِبَتْ","Jamais ses libéralités ne manquent d'enrichir la main de l'indigent : ",150,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (300,"إِنَّ الْحَيَا يُنْبِتُ الْأَزْهَارَ فِي الْأَكَمِ","Ainsi la pluie fait éclore les fleurs sur les collines. ",150,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (301,"وَلَمْ أُرِدْ زَهْرَةَ الدُّنْيَا الَّتِي اقْتَطَفَتْ","Je ne désire point de recevoir de lui les biens frivoles de ce monde, ",151,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (302,"يَدَا زُهَيْرٍ بِمَا اَثْنَىٰ عَلَىٰ هَرِمِ","Pareils à ceux dont Harim, fils de Sénan, payait les vers que Zohaïr chantait à sa louange [25] ",151,9);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (303,"يَا اَكْرَمَ الْخَلْقِ مَا لِي مَنْ اَلُوذُ بِهِ","O le plus excellent des êtres créés !",152,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (304,"سِوَاكَ عِنْدَ حُلُولِ الْحَادِثِ الْعَمِمِ","Quel autre que toi prendrai-je pour refuge en ce moment terrible, commun à tous les mortels ? ",152,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (305,"وَلَنْ يَضِيقَ رَسُولَ اللهِ جَاهُكَ بِي","Apôtre de Dieu, ta gloire ne sera point ternie par le secours que tu m'accorderas,",153,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (306,"إِذَا الْكَرِيمُ تَجَلَّىٰ بِاسْمِ مُنْتَقِمِ","Au jour où Dieu se manifestera sous le nom de vengeur : ",153,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (307,"فَإِنَّ مِنْ جُودِكَ الدُّنْيَا وَضَرَّتَهَا ","Car ce monde et le monde futur sont des effets de ta libéralité,",154,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (308,"وَمِنْ عُلُومِكَ عِلْمَ اللَّوحِ وَالْقَلَمِ","Et tous les décrets tracés par la plume éternelle sur les tablettes du Très-Haut, font partie de tes connaissances. ",154,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (309,"يَا نَفْسُ لَا تَقْنَطِي مِنْ زَلَّةٍ عَظُمَتْ","O mon âme, que la grandeur de tes fautes ne te jette pas dans le désespoir ;",155,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (310,"إِنَّ الْكَبَائِرَ فِي الْغُفْرَانِ كَاللَّمَمِ","Les plus grands crimes sont, par rapport à la clémence divine, comme les fautes les plus légères. ",155,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (311,"لَعَلَّ رَحْمَةَ رَبِّي حِينَ يَقْسِمُهَا","Au jour où le Seigneur distribuera ses miséricordes, sans doute il daignera les proportionner aux péchés de ceux qui l'auront offensé.",156,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (312,"تَأْتِي عَلَىٰ حَسَبِ الْعِصْيَانِ فِي الْقِسَمِ","O mon Dieu ! Ne permets pas que je sois trompé dans mon espérance ; ne permets pas que je sois déçu dans mes calculs ! ",156,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (313,"يَا رَبِّ وَاجْعَلْ رَجَائِي غَيْرَ مُنْعَكِسٍ","Qu'en ce monde et en l'autre ta bonté se fasse sentir à ton esclave;",157,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (314,"لَدَيْكَ وَاجْعَلْ حِسَابِي غَيْرَ مُنْخَرِمِ"," Car tout courage l'abandonne aussitôt que les dangers le menacent. ",157,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (315,"وَالْطُفْ بِعَبْدِكَ فِي الدَّارَينِ إِنَّ لَهُ","AAAA",158,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (316,"صَبْراً مَتَىٰ تَدْعُهُ الْأَهْوَالُ يَنْهَزِمِ","AAAA",158,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (317,"وَائْذَنْ لِسُحْبِ صَلَاةٍ مِنْكَ دَائِمَةٍ","AAAA",159,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (318,"عَلَى النَّبِيِّ بِمُنْهَلٍّ وَمُنْسَجِمِ","AAAA",159,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (319,"مَا رَنَّحَتْ عَذَبَاتِ الْبَانِ رَيْحُ صَباً","Aussi longtemps que le souffle des zéphyrs agitera les rameaux du ban; aussi longtemps que les conducteurs des chameaux charmeront leurs fatigues par des chansons. ",160,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (320,"وَاَطْرَبَ الْعِيسَ حَادِي الْعِيسِ بِالنَّغَمِ","AAAA",160,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (321,"ثُمَّ الرِّضَا عَنْ اَبِي بَكْرٍ وَعَنْ عُمَرٍ","AAAA",161,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (322,"وَعَنْ عَلِيٍّ وَعَنْ عُثْمَانَ ذِي الْكَرَمِ","AAAA",161,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (323,"وَالْآلِ وَالصَّحْبِ ثُمَّ التَّابِعِينَ لَهُمْ","Fais la même grâce à ses descendants, à ses compagnons, et à ceux qui leur ont succédé,",162,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (324,"اَهْلِ التُّقَىٰ وَالنَّقَىٰ وَالْحِلْمِ وَالْكَرَمِ","À ces hommes distingués par leur piété, leur pureté, leur science, et la noblesse de leurs sentiments. ",162,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (325,"يَا رَبِّ بِالْمُصْطَفَىٰ بَلِّغْ مَقَاصِدَنَا","AAAA",163,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (326,"وَاغْفِرْ لَنَا مَا مَضَىٰ يَا وَاسِعَ الْكَرَمِ","AAAA",163,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (327,"وَاغْفِرْ إلَـٰهِي لِكُلِّ الْمُسْلِمِينَ بِمَا","AAAA",164,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (328,"يَتْلُونَ فِي الْمَسْجِدِ الْأَقْصَىٰ وَفِي الْحَرَمِ","AAAA",164,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (329,"بِجَاهِ مَنْ بَيْتُهُ فِي طَيْبَةٍ حَرَمٌ","AAAA",165,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (330,"وَإِسْمُهُ قَسَمٌ مِنْ اَعْظَمِ الْقَسَمِ","AAAA",165,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (331,"وَهــٰذه بُرْدَةُ الْمُخْتَارِ قَدْ خُتِمَتْ","AAAA",166,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (332,"وَالْحَمْدُ لله فِي بَدْءٍ وَفِي خَتَمِ","AAAA",166,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (333,"اَبْيَاتُهَا قَدْ اَتَتْ سِتِّينَ مَعْ مِائَةٍ","AAAA",167,10);
INSERT or IGNORE INTO kalam (id,text,text_fr,couplet,baid) VALUES (334,"فَرِّجْ بِهَا كَرْبَنَا يَا وَسِعَ الْكَرَمِ","AAAA",167,10);